version: '3'

services:
  rabbit-mq:
    image: rabbitmq:3-management
      # volumes:
      #   - rabbitmq:/var/lib/rabbitmq
    environment:
      - TCP_PORTS=15672, 5672
    ports:
      - 15672:15672
      - 5672:5672